### ISSUE TITLE
Add a Query route

### ISSUE THREAD

**Issue by yDu98** [CSCI-GA-2820-FA23-003/wishlists#60] opened 2023-10-29 06:57 UTC
As a Customer
I need to filter items in my wishlist by specific criteria
So that I can quickly find and manage the items I'm interested in

**Details and Assumptions**
- There exists a model for items in a wishlist
- There exists a database to request item information in a wishlist
- The filtering criteria could include attributes such as price, category, name, or any other relevant attribute.

**Acceptance Criteria**
```gherkin
Given I am a customer
When I send a request to filter items for a specific wishlist ID by specific criteria
Then I receive a list of items in that wishlist that match the filtering criteria
```

**Comment by studentgrad0419** [comment] 2023-10-29 17:23
Hi Yanfeng, I think this is a duplicate of #59 and #58.

**Comment by jay-goettelmann-nyu** [comment] 2023-10-30 02:10
Duplicate story.

**Closed** 2023-10-30 02:09 UTC
Labels: duplicate
