### ISSUE TITLE
Set up a Database For Wishlists

### ISSUE THREAD

**Issue by studentgrad0419** [CSCI-GA-2820-FA23-003/wishlists#15] opened 2023-09-28 22:18 UTC
**As a** [Administrator]
**I need** [a way to have user wishlist data to persist]  
**So that** [it can be referenced in case of technical issues and allow for customer support]  
   
 ### Details and Assumptions
 * Wishlists data includes lists of Wishlist per customer
 * Wishlist item data we can retrieve includes sku, description, quantity, price per unit (See related Model story for full column/attribute details)
 * Underlying DB is PostgreSQL
 * We can access and edit it through a connection string URI 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given we have a database accessible through a URI
 When I perform a query through a URI
 Then I receive the query result
```

**Comment by studentgrad0419** [comment] 2023-10-01 20:30
Add a seperate issue for items, seperate from this

**Comment by jay-goettelmann-nyu** [comment] 2023-10-04 22:08
Duplicate of #4

**Closed by jay-goettelmann-nyu** 2023-10-04 22:08 UTC
Labels: duplicate
